<?php

namespace AppBundle\Repository;

/**
 * DepartmentAuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentAuthorizationRepository extends \Doctrine\ORM\EntityRepository {
    
}
