<?php

namespace AppBundle\Repository;

/**
 * ProgressInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressInfoRepository extends \Doctrine\ORM\EntityRepository {
    
}
