<?php

namespace AppBundle\Repository;

/**
 * QuizResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizResultsRepository extends \Doctrine\ORM\EntityRepository {
    
}
