<?php

namespace AppBundle\Repository;

/**
 * QuizGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizGroupRepository extends \Doctrine\ORM\EntityRepository {
    
}
