<?php

namespace AppBundle\Repository;

/**
 * QuizTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizTypeRepository extends \Doctrine\ORM\EntityRepository {
    
}
