<?php

namespace AppBundle\Repository;

/**
 * QuizGroupQuizListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizGroupQuizListRepository extends \Doctrine\ORM\EntityRepository {
    
}
