<?php

namespace AppBundle\Repository;

/**
 * QuizAuthorizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizAuthorizationRepository extends \Doctrine\ORM\EntityRepository {
    
}
