<?php

namespace AppBundle\Repository;

/**
 * QuizAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
