<?php

namespace AppBundle\Repository;

/**
 * ReportTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportTypeRepository extends \Doctrine\ORM\EntityRepository {
    
}
