<?php

namespace AppBundle\Repository;

/**
 * UserQuizGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQuizGroupRepository extends \Doctrine\ORM\EntityRepository {
    
}
