# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.custom_security:
        class: AppBundle\CustomSecurity\CustomSecurity
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
